export const layout = {
  keyAspectRatio: 1.08,
  keyHeight: 74,
  compactKeyHeight: 56,
  keyMinSize: 58,
  compactKeyMinHeight: 52,
  tallKeyMinHeight: 124,
  screenMaxWidth: 430,
  compactScreenHeight: 700,
  compactScreenWidth: 360,
  screenHorizontalPadding: 22,
  compactScreenHorizontalPadding: 14,
  topBarMinHeight: 44,
  operatorRailWidth: 70,
  compactOperatorRailWidth: 64,
  zeroKeyFlex: 2.02,
  accentDotSize: 7,
  accentLineWidth: 26,
  accentLineHeight: 5,
  resultMinimumFontScale: 0.58,
  resultMaxFontMultiplier: 1,
  textMaxFontMultiplier: 1.15,
  keyMaxFontMultiplier: 1.2
} as const;
