export const layout = {
  keyAspectRatio: 1.08,
  keyHeight: 64,
  compactKeyHeight: 52,
  keyMinSize: 54,
  compactKeyMinHeight: 50,
  tallKeyMinHeight: 124,
  screenMaxWidth: 430,
  compactScreenHeight: 700,
  compactScreenWidth: 360,
  screenHorizontalPadding: 20,
  compactScreenHorizontalPadding: 14,
  topBarMinHeight: 64,
  operatorRailWidth: 66,
  compactOperatorRailWidth: 60,
  zeroKeyFlex: 2.02,
  accentDotSize: 8,
  accentLineWidth: 24,
  accentLineHeight: 4,
  resultMinimumFontScale: 0.58,
  resultMaxFontMultiplier: 1,
  textMaxFontMultiplier: 1.15,
  keyMaxFontMultiplier: 1.2
} as const;
